### PR TITLE
Replaced / with ___ to fix build issues

### PR DESCRIPTION
**Pull request by acuthbert**
A simple solution to issues #15.

### CODE REVIEW

**Comment by fezfez** [comment]
+1

**Comment by mkuenstner** [comment]
:+1: my phpunit-test work again :)

**Comment by DavidA2014** [comment]
This would probably fix an issue I have. Thanks. Just wondered why you chose to have multiple '_' instead of just one?

**Comment by eMerzh** [comment]
I ran into this issue too! please merge that fix :)
Please

**Comment by wwasser** [comment]
Please integrate and realease

**Comment by t-stamm** [comment]
4 of 5 PRs are about this issue. Why is this still not fixed?

**Comment by johnhamelink** [comment]
Please merge this - this is wreaking havok with my makefiles :cry:

**Comment by maciejkra** [comment]
:+1:

**Comment by mjdetullio** [comment]
I don't be merging this since I am working on consuming the Branch API for this plugin.  The code changed here will no longer be part of this plugin.

**Comment by acuthbert** [comment]
@DavidA2014 the multiple underscores was just in case there was a clash with another branch that actually used a single underscore. Unlikely, but even more unlikely if we replace the / with two underscores :)

**Comment by deece** [comment]
Could we merge this for now, until it the code is obsoleted? the %s in the paths confuse make recipes that use % as a wildcard, and since they are in third party projects, I can't easily fix it.

**Comment by dbelyaev** [comment]
@mjdetullio so, you are using Branch API in newest releases? It is only to ask maintainer of Branch API to resolve encoded slash issues, is it right?

**Comment by pruiz** [comment]
@mjdetullio May you consider merging this (or any of the other similar pullreqs) while changes relative to branch-api are still being working on?

**Comment by mjdetullio** [comment]
There's a migration path to consider for all existing jobs.  Syncing branches will generate a duplicate job for any branch containing a slash.

**Comment by mjdetullio** [comment]
No longer applies to current tree.

**Comment by pruiz** [comment]
@mjdetullio we do (really) understand your point, but this is an stopper issue for many of us, preventing use of your (otherwise) great plugin.

As such, providing us with a temporal solution (like one of the many proposed pull-reqs) sounds better than having to wait indefinitely.. :?

**Comment by mjdetullio** [comment]
And I understand it's a showstopper for some platforms, but the fact of the matter is that all PRs so far have been "hacks".  There are obvious issues with name collision and no one has written the migration path for existing plugin installs.

Implementing prior to using the branch-api-plugin would be nightmare for maintainability, since the current iteration of that plugin would revert this type of change.

Regardless, please move discussion to https://issues.jenkins-ci.org/browse/JENKINS-34564 (preferably) or https://github.com/jenkinsci/branch-api-plugin/pull/44

**Pull request closed without merging**
