### PR TITLE
[JENKINS-36896]: Fixed symlink path unsupported for Windows.

### PR DESCRIPTION
**Pull request by Dohbedoh**

### CODE REVIEW

**Comment by Dohbedoh** [comment]
@reviewByBees

**Comment by jglick** [comment]
Whether or not this fix works, it seems likely that the real problem is inappropriate design in the plugin’s migration code. You should not be iterating directories in `$JENKINS_HOME`.

**Comment by vaimr** [comment]
This is really problem in OS Windows. After jenkins restart I forsed to clean all bad files with mask "*.symlink" otherwise jenkins not start

**Comment by jsnmc** [comment]
Any ETA on this fix?  I hit the startup crash every time I restart the server.

**Pull request merged**
